spring:
  application:
    name: springAI

  data:
    mongodb:
      # uri: mongodb://root:secret@mongodb:27017/mydatabase?authSource=admin
      uri: mongodb://root:secret@localhost:27017/mydatabase?authSource=admin

  docker:
    compose:
      enabled: false